language: java
services:
  - docker
jdk:
  - openjdk17

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull fikadu116/dockerhub:myfirstreservationsystem

script:
  - ./mvnw clean install

